### ISSUE TITLE
Estrenos not working

### ISSUE THREAD

**Issue by deimidis** [arsat/odeon-kodi#2]
I installed the addon through the packet manager and everything works fine but I can't see the movies I paid in Estrenos. It didn't show in the menu or if I add the movie to «Mi sala», it shows all the other stuff, but not the movie

**Comment by enderf** [comment]
We uploaded a new version [1.3.0] which includes Premieres and My Rentals sections. After renting a film through the web or mobile app you should be able to use the Kodi plugin to watch it.
