### ISSUE TITLE
Before update favourite things at Mi Sala didn't play

### ISSUE THREAD

**Issue by deimidis** [arsat/odeon-kodi#3]
After the new update, series that were at «Mi Sala» didn't play. Neither taking out from Mi Sala not inside the folder. Other series and films works as expected, including new addition to Mi Sala.

Por si acso en castellano para expresarme mejor. El contenido que había sumado a Mi Sala antes de la actualización no se reproduce. Cuando le doy play aparece un cartel rojo que dice que revise la información de registro, antes de entrar a la selección de capítulos.

Un corto agregado después de la actualización funcionó bien. La misma serie (Romanos) fuera de Mi Sala tampoco funciona, pero si otras.

**Comment by enderf** [comment]
Hola Guillermo, es un bug. Mañana subo la versión corregida.
