### ISSUE TITLE
Control asked to focus

### ISSUE THREAD

**Issue by mcongom** [arsat/odeon-kodi#4]
Hola, estoy usando Kodi 17.5 en kubuntu 16.04 y al iniciar el addon sale un error "Error: Control 55 in Window 10025 has been asked to focus, but it cant". A que se debe?
Gracias!

**Comment by enderf** [comment]
Hola, no probamos con kubuntu en particular y desconozco a qué se puede
deber este error ¿Esto pasa siempre? ¿Probaste con alguna otra versión de
Kodi? Nos sería útil contar con el .log de Kodi (en modo debug).
Saludos!

2017-11-05 14:28 GMT-03:00 mcongom <notifications@github.com>:

**Comment by mcongom** [comment]
Indagando veo que se trata de un warning y no un error. El add on funciona perfectamente. Gracias.
