### ISSUE TITLE
Content playback not working 

### ISSUE THREAD

**Issue by arigit** [arsat/odeon-kodi#5]
As described by various users in the official addon thread,

https://forum.kodi.tv/showthread.php?tid=296742

content playback is broken. Addon login and content browsing works fine, but playback errors out.
This is not due to geo-blocking: a desktop linux PC accessing cine.ar and using the same credentials, on the same local network, can browse and play the content with no issue. 

Seems like a problem with the playback url that's generated.

From one of the logs
```

19:46:17.930 T:1962184704 NOTICE: OMXPlayerUnsuitable OMXPlayer unsuitable due to audio sink
19:46:17.939 T:1962184704 NOTICE: VideoPlayer: Opening: https://5393958088117.streamlock.net/ode...ZlOF-n7Mew
19:46:17.939 T:1962184704 WARNING: CDVDMessageQueue(player):Tongueut MSGQ_NOT_INITIALIZED
19:46:18.024 T:1486877600 NOTICE: Creating InputStream
19:46:18.750 T:1486877600 NOTICE: Creating Demuxer
19:46:48.865 T:1486877600 ERROR: OpenDemuxStream - Error creating demuxer
19:46:48.865 T:1486877600 NOTICE: CVideoPlayer::OnExit()
19:46:48.866 T:1962184704 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.odeon/?action=play&pid=5841e45ae9d43e032cece404&source=INCAA&sid=703]
19:46:48.867 T:1962184704 NOTICE: CVideoPlayer::CloseFile()
19:46:48.867 T:1962184704 NOTICE: VideoPlayer: waiting for threads to exit
19:46:48.867 T:1962184704 NOTICE: VideoPlayer: finished waiting

```

**Comment by enderf** [comment]
As far as I know this error happens on Raspberry Pi (LibreElec or others). We have tested the addon on Android (many), Linux and Windows and it is working OK.
Perhaps there is a problem with the codecs decoding of Raspberry Pi libraries. I don´t know how to debug or correct that. The Kodi client code in Python is very standard and we cannot change the backend (media server, encoding, etc.)

**Comment by enderf** [comment]
Sometimes there is a time-out from streamlock.net service, part from the Wowza suite used in the streaming process.  Doesn´t happen always and there is little to do from the plugin side.
I'm closing the issue.
