### ISSUE TITLE
Support for Kodi 19 by porting the addon to Python 3

### ISSUE THREAD

**Issue by OscarL** [arsat/odeon-kodi#6]
Since Kodi 19 dropped support for Python 2 based addons, we lost access to Cine.Ar Play.

Any chance of getting an updated version?

Thanks in advance!

**Comment by enderf** [comment]
Here it is. Please give it a try.
https://kodi.tv/addons/matrix/plugin.video.cinear

**Comment by OscarL** [comment]
@enderf: Seems to be working OK! Thanks a lot!
